/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_test_Hello_JNI */

#ifndef _Included_hello_test_Hello_JNI
#define _Included_hello_test_Hello_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_test_Hello_JNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hello_1test_Hello_1JNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
